<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Promise几个关键问题</title>
</head>
<body>
  <script>
    // 1. 如何改变promise的状态？ （三种情况）
    const promise = new Promise((resolve, reject) => {
      // resolve(1) // promise变为resolved成功状态 value = 1
      // reject(2) // promise变为rejected失败状态 reason = 2
      // throw new Error('出错了') // promise变为rejected失败状态， reason为抛出的error
      throw 3 // promise变为rejected 失败状态 reason = 3
    })


    // 2. 一个promise指定多个成功/失败回调函数，都会调用吗？  是的！！！都会调用
    // 当promise改变为对应状态时都会调用
    promise.then(
      value => {},
      reason => {console.log('reason', reason)}
    )
    promise.then(
      value => {},
      reason => {console.log('reason2', reason)}
    )

    console.log('---改变promise状态和指定回调函数谁先谁后---1') // 同步执行----1
    // 3. 改变promise状态和指定回调函数谁先谁后
    // 3.1 常规：先指定回调函数，后改变的状态
    new Promise((resolve, reject) => {
      setTimeout(() => { 
        resolve(1) // 后改变的状态（同时指定数据），异步执行回调函数
      }, 1000)
    }).then( // 先指定回调函数， 保存当前指定的回调函数
      value => {console.log('value3', value)}, 
      reason => {console.log('reason3', reason)}
    )
    // 3.2 先改变状态，后指定回调函数
    // 方式一
    new Promise((resolve, reject) => {
        resolve(2) // 先改变的状态（同时指定数据）
    }).then( // 后指定回调函数， 异步执行回调函数
      value => {console.log('value4', value)}, 
      reason => {console.log('reason4', reason)}
    )
    console.log('----2----')  // 同步执行----2
    // 方式二
    const p1 = new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(3)
      }, 1000);
    })
    setTimeout(() => {
      value => {console.log('value5', value)}, 
      reason => {console.log('reason5', reason)}
    }, 1100);


    // 重点面试题
    // 4. promise.then() 返回的新promise的结果状态由什么决定？ 由then()指定的回调函数执行的结果决定
    new Promise((resolve, reject) => {
      resolve(1);
      // reject(1);
    }).then(
      value => {
        console.log('onResolved1()', value)
        // return 2
        // return Promise.resolve(3)
        // return Promise.reject(4)
        // throw 5
        // 什么都不返回，就是返回了一个undefined 
      },
      reason => {console.log('onRejected1()', reason)}
    ).then(
      value => {console.log('onResolved2()', value)},
      reason => {console.log('onRejected2()', reason)}
    )


    // 5. promise如何串联多个任务
    new Promise((resolve, reject) => {
      setTimeout(() => {
        console.log('执行任务1（异步）');
        resolve(1);
      }, 1000);
    }).then(
      value => {
        console.log('任务1的结果:', value);
        console.log('执行任务2（同步）');
        // resolve(2);
        return Promise.resolve(2)
      }
    ).then(
      value => {
        console.log('任务2的结果', value);
        return new Promise((resolve, reject) => {
        // 启动任务3（异步）
          setTimeout(() => {
            console.log('执行任务3（异步）');
            resolve(3)
          }, 1000);
        })
      }
    ).then(
      value => {
        console.log('任务3的结果：', value);
      }
    )


    // 6. promise异常穿透（传透）
    new Promise((resolve, reject) => {
      // resolve(1)
      reject(1)
    }).then(
      value => {
        console.log('onResolved1()', value)
        return 2
      },
      // reason => {throw reason} 默认的
      // reason => Promise.reject(reason)
    ).then(
      value => {
        console.log('onResolved2()', value)
        return 3
      }
    ).then(
      value => {
        console.log('onResolved3()', value)
      }
    ).catch(reason => {
      console.log('onRejected1()', reason)
    })

    
    // 7. 中断promise链
    new Promise((resolve, reject) => {
      // resolve(1)
      reject(1)
    }).then(
      value => {
        console.log('onResolved1()', value)
        return 2
      }
    ).then(
      value => {
        console.log('onResolved2()', value)
        return 3
      }
    ).then(
      value => {
        console.log('onResolved3()', value)
      }
    ).catch(reason => {
      console.log('onRejected1()', reason)
      return newPromise(() => {}) // 返回一个pending的promise   中断promise链
    }).then(
      value => {
        console.log('onResolved4()', value)
      },
      reason => {
        console.log('onRejected2()', reason)
      }
    )



  </script>
</body>
</html>